[package]
name = "vectores"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4.0"
actix-web = "3.3.2"
actix-rt = "2.3.0"
serde = "1.0"
serde_json = "1.0"
actix-cors = "0.5" 
